In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [ ]:
cd drive/

/content/drive


In [ ]:
cd My Drive

/content/drive/My Drive


In [ ]:
cd 520

/content/drive/My Drive/520


In [ ]:
import csv 
import numpy as np
import pandas as pd
fields=[]
rows= []
distribution = [] 
parent_rank = [] 
def success():
    weight_of_actions = np.array(probabilities)
    sum_of_probabilities = weight_of_actions.sum()
    np.multiply(weight_of_actions, 1 / sum_of_probabilities, weight_of_actions)
    cum_probabilities = weight_of_actions.cumsum()
    x = random()
    for i in range(len(cum_probabilities)):
        if x < cum_probabilities[i]:
            return ActualActions[i]
with open("input.csv", 'r') as csvfile: 
    # creating a csv reader object 
    csvreader = csv.reader(csvfile)
    for row in csvreader: 
        rows.append(row) 
    print(len(rows))
    for i in range(len(rows)):
      distribution.append(success())
    print(distribution[:10])
data=list()
for i in range(len(rows)):
  data.append(((distribution[i]),int(rows[i][0])))
csvfile.close()
with open("output.csv", 'w') as csvfile:
  csvwriter=csv.writer(csvfile) 
  csvwriter.writerows(data)
csvfile.close()

1048576
[2, 0, 2, 2, 0, 0, 1, 0, 2, 2]


In [ ]:
def loadcsv():
  with open("input.csv", 'r') as csvfile:
    csvreader = csv.reader(csvfile)
    dataset=list(csvreader)
    for i in range(len(dataset)):
      dataset[i] = [float(x) for x in dataset[i]]
    csvfile.close()
    return dataset

In [ ]:
import random as random
def splitDataset(dataset, splitRatio):
  trainSize = int(len(dataset) * splitRatio)
  trainSet = []
  copy = list(dataset)
  while len(trainSet) < trainSize:
    index = random.randrange(len(copy))
    trainSet.append(copy.pop(index))
  return [trainSet, copy]

In [ ]:
def separateByClass(dataset):
  separated = {}
  for i in range(len(dataset)):
   vector = dataset[i]
  if (vector[-1] not in separated):
    separated[vector[-1]] = []
    separated[vector[-1]].append(vector)
  return separated

In [ ]:
def mean(numbers):
  return sum(numbers)/float(len(numbers))

In [ ]:
import math
def stdev(numbers):
  avg = mean(numbers)
  variance = sum([pow(x-avg,2) for x in numbers])/(len(numbers))
  return math.sqrt(variance)

In [ ]:
def summarize(dataset):
  summaries = [(mean(attribute), stdev(attribute)) for attribute in zip(*dataset)]
  del summaries[-1]
  return summaries

In [ ]:
def summarizeByClass(dataset):
  separated = separateByClass(dataset)
  summaries = {}
  for classValue, instances in separated.items():
    summaries[classValue] = summarize(instances)
  return summaries

In [ ]:
def calculateProbability(x, mean, stdev):
  exponent = math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
  return (1/(math.sqrt(2*math.pi)*stdev))*exponent

In [ ]:
def calculateClassProbabilities(summaries, inputVector):
  probabilities = {}
  for classValue, classSummaries in summaries.items():
    probabilities[classValue] = 1
  for i in range(len(classSummaries)):
    mean, stdev = classSummaries[i]
    x = inputVector[i]
    probabilities[classValue] *= calculateProbability(x, mean, stdev)
  return probabilities

In [ ]:
def predict(summaries, inputVector):
  probabilities = calculateClassProbabilities(summaries, inputVector)
  bestLabel, bestProb = None, -1
  for classValue, probability in probabilities.items():
    if bestLabel is None or probability > bestProb:
      bestProb = probability
      bestLabel = classValue
  return bestLabel

In [ ]:
def getPredictions(summaries, testSet):
  predictions = []
  for i in range(len(testSet)):
    result = predict(summaries, testSet[i])
    predictions.append(result)
  return predictions

In [ ]:
def getAccuracy(testSet, predictions):
  correct = 0
  for x in range(len(testSet)):
    if testSet[x][-1] == predictions[x]:
      correct += 1
  return (correct/float(len(testSet)))*100.0

In [ ]:
splitRatio = 0.8
dataset = loadcsv()
trainingSet, testSet = splitDataset(dataset, splitRatio)
print('Split {0} rows into train = {1} and test = {2} rows'.format(len(dataset),len(trainingSet),len(testSet)))
  #prepare model
summaries = summarizeByClass(trainingSet)
  #test model
predictions = getPredictions(summaries, testSet)
accuracy = getAccuracy(testSet, predictions)
print('Accuracy: {0}%'.format(accuracy))


Split 1048576 rows into train = 838860 and test = 209716 rows
Accuracy: 88.50206946537222%


In [ ]:
import csv

In [ ]:
from sklearn import datasets
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
dataset = loadcsv()
splitRatio=0.5
trainingSet, testSet = splitDataset(dataset, splitRatio)
model = GaussianNB()
model.fit(trainingSet, testSet)

expected = testSet
predicted = model.predict(trainingSet)


print(metrics.classification_report(expected, predicted))
print(metrics.confusion_matrix(expected, predicted))

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


              precision    recall  f1-score   support

         0.0       0.88      0.89      0.89    463949
         1.0       0.00      0.00      0.00     60327
         2.0       0.00      0.00      0.00         7
         3.0       0.00      0.00      0.00         2
         5.0       0.00      0.00      0.00         1
         8.0       0.00      1.00      0.00         1
        10.0       0.00      0.00      0.00         1

    accuracy                           0.78    524288
   macro avg       0.13      0.27      0.13    524288
weighted avg       0.78      0.78      0.78    524288

[[411031      0      0     15      0  52903      0]
 [ 53437      0      0      3      0   6887      0]
 [     7      0      0      0      0      0      0]
 [     1      0      0      0      0      1      0]
 [     1      0      0      0      0      0      0]
 [     0      0      0      0      0      1      0]
 [     1      0      0      0      0      0      0]]


In [ ]:
# k-nearest neighbors on the Iris Flowers Dataset
from random import seed
from random import randrange
from csv import reader
from math import sqrt
 
# Load a CSV file
def load_csv(filename):
	dataset = list()
	with open(filename, 'r') as file:
		csv_reader = reader(file)
		for row in csv_reader:
			if not row:
				continue
			dataset.append(row)
	return dataset
 
# Convert string column to float
def str_column_to_float(dataset, column):
	for row in dataset:
		row[column] = float(row[column].strip())
 
# Convert string column to integer
def str_column_to_int(dataset, column):
	class_values = [row[column] for row in dataset]
	unique = set(class_values)
	lookup = dict()
	for i, value in enumerate(unique):
		lookup[value] = i
	for row in dataset:
		row[column] = lookup[row[column]]
	return lookup
 
# Find the min and max values for each column
def dataset_minmax(dataset):
	minmax = list()
	for i in range(len(dataset[0])):
		col_values = [row[i] for row in dataset]
		value_min = min(col_values)
		value_max = max(col_values)
		minmax.append([value_min, value_max])
	return minmax
 
# Rescale dataset columns to the range 0-1
def normalize_dataset(dataset, minmax):
	for row in dataset:
		for i in range(len(row)):
			row[i] = (row[i] - minmax[i][0]) / (minmax[i][1] - minmax[i][0])
 
# Split a dataset into k folds
def cross_validation_split(dataset, n_folds):
	dataset_split = list()
	dataset_copy = list(dataset)
	fold_size = int(len(dataset) / n_folds)
	for _ in range(n_folds):
		fold = list()
		while len(fold) < fold_size:
			index = randrange(len(dataset_copy))
			fold.append(dataset_copy.pop(index))
		dataset_split.append(fold)
	return dataset_split
 
# Calculate accuracy percentage
def accuracy_metric(actual, predicted):
	correct = 0
	for i in range(len(actual)):
		if actual[i] == predicted[i]:
			correct += 1
	return correct / float(len(actual)) * 100.0
 
# Evaluate an algorithm using a cross validation split
def evaluate_algorithm(dataset, algorithm, n_folds, *args):
	folds = cross_validation_split(dataset, n_folds)
	scores = list()
	for fold in folds:
		train_set = list(folds)
		train_set.remove(fold)
		train_set = sum(train_set, [])
		test_set = list()
		for row in fold:
			row_copy = list(row)
			test_set.append(row_copy)
			row_copy[-1] = None
		predicted = algorithm(train_set, test_set, *args)
		actual = [row[-1] for row in fold]
		accuracy = accuracy_metric(actual, predicted)
		scores.append(accuracy)
	return scores
 
# Calculate the Euclidean distance between two vectors
def euclidean_distance(row1, row2):
	distance = 0.0
	for i in range(len(row1)-1):
		distance += (row1[i] - row2[i])**2
	return sqrt(distance)
 
# Locate the most similar neighbors
def get_neighbors(train, test_row, num_neighbors):
	distances = list()
	for train_row in train:
		dist = euclidean_distance(test_row, train_row)
		distances.append((train_row, dist))
	distances.sort(key=lambda tup: tup[1])
	neighbors = list()
	for i in range(num_neighbors):
		neighbors.append(distances[i][0])
	return neighbors
 
# Make a prediction with neighbors
def predict_classification(train, test_row, num_neighbors):
	neighbors = get_neighbors(train, test_row, num_neighbors)
	output_values = [row[-1] for row in neighbors]
	prediction = max(set(output_values), key=output_values.count)
	return prediction
 
# kNN Algorithm
def k_nearest_neighbors(train, test, num_neighbors):
	predictions = list()
	for row in test:
		output = predict_classification(train, row, num_neighbors)
		predictions.append(output)
	return(predictions)
 
# Test the kNN on the Iris Flowers dataset
seed(1)
filename = 'output.csv'
dataset = load_csv(filename)
for i in range(len(dataset[0])-1):
	str_column_to_float(dataset, i)
# convert class column to integers
str_column_to_int(dataset, len(dataset[0])-1)
# evaluate algorithm
n_folds = 2
num_neighbors = 3
scores = evaluate_algorithm(dataset, k_nearest_neighbors, n_folds, num_neighbors)
print('Scores: %s' % scores)
print('Mean Accuracy: %.3f%%' % (sum(scores)/float(len(scores))))